const featured=[{"id":1,"name":"Trilia","description":"External constriction of right middle finger, subs encntr","last_updated":"7/22/2022","page_no":1,"type":"Gembucket","used":"22807","hashtags":"#d14"},
{"id":2,"name":"Meeveo","description":"Displ oblique fx shaft of l fibula, 7thM","last_updated":"6/24/2022","page_no":2,"type":"Span","used":"608","hashtags":"#e48"},
{"id":3,"name":"Dabvine","description":"Personal history of malignant neoplasm of kidney","last_updated":"10/16/2022","page_no":3,"type":"Sonair","used":"409","hashtags":"#10b"},
{"id":4,"name":"Pixoboo","description":"Unspecified fracture of shaft of unspecified tibia, sequela","last_updated":"2/4/2023","page_no":4,"type":"Home Ing","used":"60166","hashtags":"#57c"},
{"id":5,"name":"Buzzshare","description":"Age-rel osteopor w crnt path fx, verteb, 7thP","last_updated":"5/12/2024","page_no":5,"type":"Quo Lux","used":"896","hashtags":"#497"},
{"id":6,"name":"Dabjam","description":"Snsrnrl hear loss, uni, right ear, w unrestr hear cntra side","last_updated":"12/10/2022","page_no":6,"type":"Zontrax","used":"5","hashtags":"#62d"},
{"id":7,"name":"Brightdog","description":"Lacrimal gland dislocation","last_updated":"4/22/2024","page_no":7,"type":"Konklux","used":"8","hashtags":"#d7b"},
{"id":8,"name":"Eidel","description":"Lacerat flxr musc/fasc/tend r little fngr at forarm lv, sqla","last_updated":"5/3/2023","page_no":8,"type":"Stim","used":"23344","hashtags":"#80e"},
{"id":9,"name":"Centizu","description":"Central retinal vein occlusion, right eye, stable","last_updated":"10/15/2023","page_no":9,"type":"Hatity","used":"904","hashtags":"#b2f"},
{"id":10,"name":"Thoughtworks","description":"Supervision of high risk pregnancy, unspecified","last_updated":"3/27/2023","page_no":10,"type":"Span","used":"0054","hashtags":"#b12"},
{"id":11,"name":"Edgeify","description":"Displaced bicondylar fracture of left tibia","last_updated":"8/20/2022","page_no":11,"type":"Holdlamis","used":"356","hashtags":"#e3b"},
{"id":12,"name":"Skimia","description":"Rheumatoid vasculitis w rheumatoid arthritis of left ank/ft","last_updated":"6/26/2024","page_no":12,"type":"Gembucket","used":"06","hashtags":"#83e"},
{"id":13,"name":"Meezzy","description":"Toxic effect of unspecified alcohol, assault, subs encntr","last_updated":"7/21/2022","page_no":13,"type":"Span","used":"1875","hashtags":"#1f0"},
{"id":14,"name":"Skynoodle","description":"Puncture wound w/o foreign body of unsp part of head, init","last_updated":"6/15/2024","page_no":14,"type":"Kanlam","used":"409","hashtags":"#21c"},
{"id":15,"name":"Rooxo","description":"Laceration of radial artery at wrs/hnd lv of left arm","last_updated":"1/23/2023","page_no":15,"type":"Sub-Ex","used":"75512","hashtags":"#d26"},
{"id":16,"name":"Dynava","description":"Other specified health status","last_updated":"1/29/2024","page_no":16,"type":"Solarbreeze","used":"2900","hashtags":"#c2d"},
{"id":17,"name":"Brainlounge","description":"Calcific tendinitis, unspecified forearm","last_updated":"5/23/2024","page_no":17,"type":"Span","used":"2923","hashtags":"#9a7"},
{"id":18,"name":"Yambee","description":"Sublux of symphysis (pubis) in preg, chldbrth and the puerp","last_updated":"11/26/2022","page_no":18,"type":"Fixflex","used":"44","hashtags":"#d37"},
{"id":19,"name":"Youfeed","description":"Tuberculosis complicating pregnancy, first trimester","last_updated":"8/4/2023","page_no":19,"type":"Zoolab","used":"0962","hashtags":"#db3"},
{"id":20,"name":"Kamba","description":"Hb-SS disease with splenic sequestration","last_updated":"10/20/2022","page_no":20,"type":"Namfix","used":"7","hashtags":"#5f1"},
{"id":21,"name":"Jaxnation","description":"Abnormal results of cardiovascular function studies","last_updated":"9/24/2022","page_no":21,"type":"Zontrax","used":"96967","hashtags":"#da3"},
{"id":22,"name":"Yacero","description":"Laceration without foreign body of unspecified forearm","last_updated":"5/9/2023","page_no":22,"type":"Solarbreeze","used":"06","hashtags":"#c0b"},
{"id":23,"name":"Thoughtsphere","description":"Displacement of int fix of left femur, sequela","last_updated":"2/14/2024","page_no":23,"type":"Tresom","used":"92","hashtags":"#8bf"},
{"id":24,"name":"Dazzlesphere","description":"Occ of anml-drn vehicle injured in collisn with same, subs","last_updated":"6/25/2024","page_no":24,"type":"Y-find","used":"41934","hashtags":"#158"},
{"id":25,"name":"Devshare","description":"Unsp fibrinolysis-affecting drugs","last_updated":"7/10/2023","page_no":25,"type":"Zaam-Dox","used":"95","hashtags":"#852"},
{"id":26,"name":"Jaxbean","description":"Moderate laceration of body of pancreas","last_updated":"8/5/2022","page_no":26,"type":"Cardify","used":"4690","hashtags":"#785"},
{"id":27,"name":"Bubblemix","description":"Major depressive disorder, recurrent","last_updated":"8/24/2024","page_no":27,"type":"Andalax","used":"8","hashtags":"#a64"},
{"id":28,"name":"Devcast","description":"Nail disorders","last_updated":"10/6/2022","page_no":28,"type":"Greenlam","used":"25787","hashtags":"#f98"},
{"id":29,"name":"Cogidoo","description":"Anterior dislocation of lens, right eye","last_updated":"4/27/2024","page_no":29,"type":"Keylex","used":"04","hashtags":"#eb7"},
{"id":30,"name":"Rhyzio","description":"Disp fx of anterior column of right acetabulum, init","last_updated":"8/1/2022","page_no":30,"type":"Latlux","used":"78","hashtags":"#ed7"},
{"id":31,"name":"Cogidoo","description":"Maternal care for malpresentation of fetus, unsp, fetus 1","last_updated":"10/12/2023","page_no":31,"type":"Zamit","used":"610","hashtags":"#8a2"},
{"id":32,"name":"Babbleopia","description":"Terrorism w chemical weapons, publ sfty offcl injured","last_updated":"8/22/2024","page_no":32,"type":"Transcof","used":"25794","hashtags":"#7a6"},
{"id":33,"name":"Jabbercube","description":"Other fracture of right foot, init","last_updated":"8/11/2022","page_no":33,"type":"Home Ing","used":"9384","hashtags":"#6a0"},
{"id":34,"name":"Voomm","description":"Inferior dislocation of left humerus, sequela","last_updated":"10/12/2023","page_no":34,"type":"Regrant","used":"779","hashtags":"#1ad"},
{"id":35,"name":"Yakitri","description":"Tear of articular cartilage of unsp knee, current, init","last_updated":"8/16/2023","page_no":35,"type":"Toughjoyfax","used":"820","hashtags":"#a46"},
{"id":36,"name":"Vinder","description":"Inj unsp blood vessel at ankle and foot level, right leg","last_updated":"6/1/2022","page_no":36,"type":"Asoka","used":"65","hashtags":"#d7c"},
{"id":37,"name":"Oozz","description":"Monoclonal mast cell activation syndrome","last_updated":"10/5/2023","page_no":37,"type":"Bytecard","used":"69","hashtags":"#949"},
{"id":38,"name":"Meetz","description":"Minor opacity of cornea, bilateral","last_updated":"6/30/2022","page_no":38,"type":"Konklux","used":"02","hashtags":"#b43"},
{"id":39,"name":"Dabvine","description":"Nondisp intertroch fx r femr, 7thF","last_updated":"5/29/2023","page_no":39,"type":"Solarbreeze","used":"79925","hashtags":"#9e9"},
{"id":40,"name":"Innojam","description":"Nondisp fx of shaft of left clavicle, subs for fx w nonunion","last_updated":"5/16/2023","page_no":40,"type":"Keylex","used":"11028","hashtags":"#db1"},
{"id":41,"name":"Riffwire","description":"Poisoning by thrombolytic drug, accidental, sequela","last_updated":"6/2/2022","page_no":41,"type":"Sonsing","used":"5052","hashtags":"#f67"},
{"id":42,"name":"Skipfire","description":"Collapsed vert, NEC, lumbar region, subs for fx w routn heal","last_updated":"7/8/2023","page_no":42,"type":"Konklux","used":"939","hashtags":"#427"},
{"id":43,"name":"Einti","description":"Other specified mononeuropathies of right lower limb","last_updated":"5/17/2023","page_no":43,"type":"Stringtough","used":"664","hashtags":"#89a"},
{"id":44,"name":"Wordware","description":"Minor lacerat great saph at hip and thi lev, left leg, sqla","last_updated":"6/26/2024","page_no":44,"type":"Otcom","used":"80394","hashtags":"#4cc"},
{"id":45,"name":"Devshare","description":"Oth fx shaft of l ulna, 7thR","last_updated":"6/9/2024","page_no":45,"type":"Aerified","used":"303","hashtags":"#180"},
{"id":46,"name":"Bubblemix","description":"Congenital malformation of bony thorax, unspecified","last_updated":"11/24/2022","page_no":46,"type":"Andalax","used":"5","hashtags":"#745"},
{"id":47,"name":"Twitterlist","description":"Injury of cutan sensory nerve at forarm lv, unsp arm, init","last_updated":"3/6/2024","page_no":47,"type":"Kanlam","used":"842","hashtags":"#abe"},
{"id":48,"name":"Edgewire","description":"Sedatv/hyp/anxiolytc use, unsp w psychotic disorder","last_updated":"7/22/2022","page_no":48,"type":"Flexidy","used":"4","hashtags":"#819"},
{"id":49,"name":"Viva","description":"Inj muscle(s) and tendon(s) of the rotator cuff of shoulder","last_updated":"6/14/2023","page_no":49,"type":"Flexidy","used":"31542","hashtags":"#978"},
{"id":50,"name":"Tagchat","description":"Injury of medial plantar nerve","last_updated":"8/21/2024","page_no":50,"type":"Sub-Ex","used":"752","hashtags":"#a32"},
{"id":51,"name":"Agimba","description":"Nondisp seg fx shaft of rad, unsp arm, 7thD","last_updated":"12/18/2022","page_no":51,"type":"Bitchip","used":"153","hashtags":"#fea"},
{"id":52,"name":"Linkbuzz","description":"Superficial foreign body of left middle finger, subs encntr","last_updated":"2/23/2024","page_no":52,"type":"Daltfresh","used":"310","hashtags":"#98e"},
{"id":53,"name":"Jabbersphere","description":"Unspecified open wound, unspecified lower leg, subs encntr","last_updated":"6/2/2023","page_no":53,"type":"Domainer","used":"572","hashtags":"#58f"},
{"id":54,"name":"Gabcube","description":"Hydroxyapatite deposition disease, shoulder","last_updated":"1/2/2023","page_no":54,"type":"Trippledex","used":"9","hashtags":"#386"},
{"id":55,"name":"Wikido","description":"Ped on foot injured in clsn w 2/3-whl mv nontraf, sequela","last_updated":"2/12/2024","page_no":55,"type":"Stringtough","used":"6","hashtags":"#2aa"},
{"id":56,"name":"Tanoodle","description":"Contracture, left ankle","last_updated":"5/22/2023","page_no":56,"type":"Tres-Zap","used":"4551","hashtags":"#013"},
{"id":57,"name":"Oyoyo","description":"Unsp inj blood vessels at forarm lv, right arm, sequela","last_updated":"1/15/2023","page_no":57,"type":"Zamit","used":"481","hashtags":"#2ea"},
{"id":58,"name":"Tagfeed","description":"Oth surgical procedures cause abn react/compl, w/o misadvnt","last_updated":"1/24/2023","page_no":58,"type":"Flexidy","used":"99301","hashtags":"#4d7"},
{"id":59,"name":"Skilith","description":"Laceration without foreign body, unsp ankle, init encntr","last_updated":"12/7/2023","page_no":59,"type":"Tin","used":"5","hashtags":"#998"},
{"id":60,"name":"Feedspan","description":"Burn of second degree of right shoulder, subs encntr","last_updated":"1/20/2023","page_no":60,"type":"Tres-Zap","used":"94","hashtags":"#a9e"},
{"id":61,"name":"Fatz","description":"Fracture of unspecified part of scapula, left shoulder","last_updated":"8/23/2022","page_no":61,"type":"Asoka","used":"9","hashtags":"#db9"},
{"id":62,"name":"Zoozzy","description":"Reiter's disease, left ankle and foot","last_updated":"5/5/2024","page_no":62,"type":"Namfix","used":"57431","hashtags":"#530"},
{"id":63,"name":"Tagpad","description":"Contusion of unspecified urinary and pelvic organ, sequela","last_updated":"9/26/2022","page_no":63,"type":"Cardify","used":"22130","hashtags":"#c78"},
{"id":64,"name":"Podcat","description":"Stress fracture, unsp hand, subs for fx w routn heal","last_updated":"10/20/2022","page_no":64,"type":"Bitchip","used":"658","hashtags":"#521"},
{"id":65,"name":"Photobug","description":"Adverse effect of unsp systemic antibiotic, subs encntr","last_updated":"9/20/2022","page_no":65,"type":"Voyatouch","used":"603","hashtags":"#eb1"},
{"id":66,"name":"Voonte","description":"War operations involving explosion of aerial bomb","last_updated":"6/30/2024","page_no":66,"type":"Alphazap","used":"74","hashtags":"#5d2"},
{"id":67,"name":"Realcube","description":"Occup of pk-up/van injured in collision w 2/3-whl mv nontraf","last_updated":"1/11/2024","page_no":67,"type":"Zamit","used":"72625","hashtags":"#22d"},
{"id":68,"name":"Dynazzy","description":"Corrosion of third degree of left axilla, subs encntr","last_updated":"10/24/2023","page_no":68,"type":"Bitchip","used":"4769","hashtags":"#854"},
{"id":69,"name":"Innotype","description":"Burn of first degree of left ankle, sequela","last_updated":"5/12/2024","page_no":69,"type":"Duobam","used":"48","hashtags":"#eb1"},
{"id":70,"name":"Leexo","description":"Nondisp avulsion fracture of right ilium, init for opn fx","last_updated":"8/19/2022","page_no":70,"type":"Duobam","used":"78","hashtags":"#4d8"},
{"id":71,"name":"Buzzdog","description":"Galeazzi's fracture of unspecified radius","last_updated":"4/1/2023","page_no":71,"type":"Bitwolf","used":"5458","hashtags":"#b66"},
{"id":72,"name":"Zoomlounge","description":"Osseous and sublux stenosis of intvrt foramin of cerv region","last_updated":"9/5/2023","page_no":72,"type":"Ventosanzap","used":"334","hashtags":"#309"},
{"id":73,"name":"Twitternation","description":"Subluxation of T9/T10 thoracic vertebra","last_updated":"11/29/2022","page_no":73,"type":"Bytecard","used":"16805","hashtags":"#f10"},
{"id":74,"name":"Photobug","description":"Toxic effect of lead and its compounds, undetermined, init","last_updated":"5/5/2022","page_no":74,"type":"Temp","used":"5","hashtags":"#14f"},
{"id":75,"name":"Lajo","description":"Displaced unsp condyle fx lower end of right femur, sequela","last_updated":"12/4/2023","page_no":75,"type":"Matsoft","used":"5","hashtags":"#10c"},
{"id":76,"name":"Blogpad","description":"Hypertrichosis","last_updated":"1/8/2024","page_no":76,"type":"Konklab","used":"668","hashtags":"#453"},
{"id":77,"name":"Shufflester","description":"Irritant contact dermatitis due to solvents","last_updated":"10/18/2023","page_no":77,"type":"Lotstring","used":"56916","hashtags":"#2c7"},
{"id":78,"name":"Wordware","description":"Unsp injury of adductor musc/fasc/tend right thigh, sequela","last_updated":"6/7/2024","page_no":78,"type":"Daltfresh","used":"604","hashtags":"#d2b"},
{"id":79,"name":"Flipstorm","description":"Actvty,snow (alp/dwnhl) ski, snow brd, sled, tobogn & tubing","last_updated":"4/9/2023","page_no":79,"type":"Fix San","used":"7520","hashtags":"#e18"},
{"id":80,"name":"Thoughtbridge","description":"Vitreous abscess (chronic), right eye","last_updated":"11/14/2023","page_no":80,"type":"Domainer","used":"65121","hashtags":"#bd7"},
{"id":81,"name":"Skiba","description":"Poisoning by unsp hormone antagonists, self-harm, sequela","last_updated":"7/13/2022","page_no":81,"type":"Stim","used":"114","hashtags":"#aca"},
{"id":82,"name":"Plambee","description":"Unsp mtrcy rider injured in clsn w hv veh nontraf, sequela","last_updated":"7/5/2022","page_no":82,"type":"Sonsing","used":"06986","hashtags":"#e92"},
{"id":83,"name":"Flashpoint","description":"Unspecified fracture of second cervical vertebra","last_updated":"7/4/2024","page_no":83,"type":"Home Ing","used":"45679","hashtags":"#923"},
{"id":84,"name":"Tazz","description":"Nondisp fx of body of scapula, unsp shldr, init for opn fx","last_updated":"8/21/2023","page_no":84,"type":"Ronstring","used":"105","hashtags":"#22c"},
{"id":85,"name":"Voonix","description":"Unsp fracture of unsp forearm, subs for clos fx w nonunion","last_updated":"8/25/2023","page_no":85,"type":"Home Ing","used":"6728","hashtags":"#c86"},
{"id":86,"name":"Browsezoom","description":"Partial traumatic amp of unsp lower leg, level unsp, sequela","last_updated":"6/12/2024","page_no":86,"type":"Rank","used":"4972","hashtags":"#762"},
{"id":87,"name":"Wordify","description":"Hemochromatosis","last_updated":"12/25/2022","page_no":87,"type":"Lotstring","used":"7878","hashtags":"#42d"},
{"id":88,"name":"Realbuzz","description":"Low-tension glaucoma","last_updated":"1/28/2024","page_no":88,"type":"Fixflex","used":"8","hashtags":"#770"},
{"id":89,"name":"Livetube","description":"Abrasion of left shoulder","last_updated":"3/8/2024","page_no":89,"type":"Sonair","used":"9533","hashtags":"#31a"},
{"id":90,"name":"Quire","description":"Collapsed vert, NEC, thrclm region, subs for fx w routn heal","last_updated":"7/15/2022","page_no":90,"type":"Alphazap","used":"6","hashtags":"#c56"},
{"id":91,"name":"Devcast","description":"Person injured wh brd/alit from special agri vehicle, subs","last_updated":"9/21/2023","page_no":91,"type":"Overhold","used":"6","hashtags":"#3f7"},
{"id":92,"name":"LiveZ","description":"Nondisp oblique fx shaft of unsp tibia, 7thK","last_updated":"7/14/2022","page_no":92,"type":"Flowdesk","used":"09","hashtags":"#259"},
{"id":93,"name":"Chatterpoint","description":"Traum subdr hem w LOC of 1-5 hrs 59 min, init","last_updated":"11/5/2022","page_no":93,"type":"Mat Lam Tam","used":"540","hashtags":"#855"},
{"id":94,"name":"Thoughtworks","description":"Direct infct of l elbow in infec/parastc dis classd elswhr","last_updated":"5/19/2023","page_no":94,"type":"It","used":"54","hashtags":"#a47"},
{"id":95,"name":"Gigaclub","description":"Drug/chem diab with severe nonp rtnop with mclr edema, r eye","last_updated":"4/30/2023","page_no":95,"type":"Sonair","used":"44239","hashtags":"#b6a"},
{"id":96,"name":"DabZ","description":"Partial traumatic amputation of left foot, level unspecified","last_updated":"4/17/2024","page_no":96,"type":"Namfix","used":"7","hashtags":"#f85"},
{"id":97,"name":"Bluejam","description":"Lacerat flexor musc/fasc/tend unsp finger at forarm lv, sqla","last_updated":"1/22/2023","page_no":97,"type":"Bytecard","used":"675","hashtags":"#167"},
{"id":98,"name":"Meemm","description":"Benign neoplasm of unspecified lacrimal gland and duct","last_updated":"6/4/2024","page_no":98,"type":"Hatity","used":"40185","hashtags":"#bd5"},
{"id":99,"name":"Jatri","description":"Sltr-haris Type I physeal fracture of r calcaneus, sequela","last_updated":"5/24/2024","page_no":99,"type":"Bitwolf","used":"5","hashtags":"#f16"},
{"id":100,"name":"Kwilith","description":"Laceration w/o fb of left eyelid and periocular area","last_updated":"8/17/2024","page_no":100,"type":"Voyatouch","used":"5","hashtags":"#cad"},
{"id":101,"name":"Quinu","description":"Intentional self-harm by unsp larger firearm discharge","last_updated":"3/12/2023","page_no":101,"type":"Lotlux","used":"074","hashtags":"#799"},
{"id":102,"name":"Twitterworks","description":"Poisoning by barbiturates, assault","last_updated":"6/17/2022","page_no":102,"type":"Mat Lam Tam","used":"923","hashtags":"#295"},
{"id":103,"name":"Brainsphere","description":"Perst migraine aura w cereb infrc, not ntrct, w/o stat migr","last_updated":"5/13/2024","page_no":103,"type":"Stim","used":"5835","hashtags":"#079"},
{"id":104,"name":"Realcube","description":"Superficial foreign body of unsp shoulder, init encntr","last_updated":"12/1/2023","page_no":104,"type":"Quo Lux","used":"68","hashtags":"#a74"},
{"id":105,"name":"Yoveo","description":"Nondisp fx of ant wall of l acetab, subs for fx w nonunion","last_updated":"11/15/2022","page_no":105,"type":"Span","used":"4","hashtags":"#491"},
{"id":106,"name":"Buzzbean","description":"Nondisp oth extrartic fx l calcaneus, 7thG","last_updated":"3/6/2023","page_no":106,"type":"Voyatouch","used":"620","hashtags":"#3d9"},
{"id":107,"name":"Tagcat","description":"Pathological fracture, femur and pelvis","last_updated":"9/11/2023","page_no":107,"type":"Alphazap","used":"2","hashtags":"#e34"},
{"id":108,"name":"Yodoo","description":"Premature separation of placenta with oth coagulation defect","last_updated":"6/12/2024","page_no":108,"type":"Gembucket","used":"81","hashtags":"#b6a"},
{"id":109,"name":"Photospace","description":"Mech compl of indwelling urethral catheter, init","last_updated":"8/12/2023","page_no":109,"type":"Tin","used":"1","hashtags":"#b60"},
{"id":110,"name":"Bubblebox","description":"Major laceration of great saphenous at hip and thigh level","last_updated":"3/22/2024","page_no":110,"type":"Zaam-Dox","used":"573","hashtags":"#b20"},
{"id":111,"name":"Snaptags","description":"Calcific tendinitis","last_updated":"1/10/2023","page_no":111,"type":"Tin","used":"41636","hashtags":"#4e1"},
{"id":112,"name":"Browsecat","description":"Sltr-haris Type IV physeal fx phalanx of right toe, 7thD","last_updated":"4/15/2024","page_no":112,"type":"Fixflex","used":"2052","hashtags":"#192"},
{"id":113,"name":"Yabox","description":"Threat of job loss","last_updated":"4/15/2024","page_no":113,"type":"Stringtough","used":"21073","hashtags":"#a0e"},
{"id":114,"name":"Zoomdog","description":"Adverse effect of ophthalmological drugs and preparations","last_updated":"7/31/2024","page_no":114,"type":"Viva","used":"081","hashtags":"#14c"},
{"id":115,"name":"Geba","description":"Unequal limb length (acquired), unspecified site","last_updated":"7/9/2022","page_no":115,"type":"Tin","used":"63","hashtags":"#d72"},
{"id":116,"name":"Quimba","description":"Toxic effect of hydrogen cyanide, undetermined, subs encntr","last_updated":"5/2/2022","page_no":116,"type":"Job","used":"48","hashtags":"#ea2"},
{"id":117,"name":"Linktype","description":"Other fracture of right ilium","last_updated":"3/31/2024","page_no":117,"type":"Konklab","used":"1833","hashtags":"#631"},
{"id":118,"name":"Livetube","description":"Injury of oculomotor nerve, left side, subsequent encounter","last_updated":"8/20/2024","page_no":118,"type":"Biodex","used":"9032","hashtags":"#423"},
{"id":119,"name":"Photofeed","description":"Poisoning by heroin, undetermined, sequela","last_updated":"5/23/2024","page_no":119,"type":"Andalax","used":"36139","hashtags":"#940"},
{"id":120,"name":"Leexo","description":"Oth fx upper end of left ulna, init for opn fx type I/2","last_updated":"12/24/2022","page_no":120,"type":"Bytecard","used":"91","hashtags":"#c9b"},
{"id":121,"name":"Zooxo","description":"Laceration of peroneal artery, left leg, initial encounter","last_updated":"12/2/2023","page_no":121,"type":"Tres-Zap","used":"450","hashtags":"#b0b"},
{"id":122,"name":"Podcat","description":"Disease of anus and rectum, unspecified","last_updated":"4/24/2024","page_no":122,"type":"Kanlam","used":"269","hashtags":"#2e7"},
{"id":123,"name":"Zazio","description":"Mastoiditis in infec/parastc diseases classd elswhr, r ear","last_updated":"10/31/2022","page_no":123,"type":"Subin","used":"284","hashtags":"#aae"},
{"id":124,"name":"Eare","description":"Milt op involving fragments from munitions, civilian, subs","last_updated":"7/20/2022","page_no":124,"type":"Home Ing","used":"086","hashtags":"#87c"},
{"id":125,"name":"Photofeed","description":"Underdosing of aspirin, sequela","last_updated":"8/9/2022","page_no":125,"type":"Lotlux","used":"618","hashtags":"#5ef"},
{"id":126,"name":"Zooveo","description":"Telogen effluvium","last_updated":"12/23/2023","page_no":126,"type":"Y-find","used":"762","hashtags":"#f76"},
{"id":127,"name":"Ntag","description":"Eversion of lacrimal punctum","last_updated":"5/15/2023","page_no":127,"type":"Ventosanzap","used":"249","hashtags":"#5ec"},
{"id":128,"name":"Thoughtblab","description":"Corneal deposits in metabolic disorders, right eye","last_updated":"10/6/2022","page_no":128,"type":"Tin","used":"31620","hashtags":"#844"},
{"id":129,"name":"Trupe","description":"Recurrent and perst hematur w diffuse membranous glomrlneph","last_updated":"1/15/2023","page_no":129,"type":"Tin","used":"25","hashtags":"#5f5"},
{"id":130,"name":"Pixoboo","description":"Lacerat flexor musc/fasc/tend at forarm lv, left arm, subs","last_updated":"6/4/2024","page_no":130,"type":"Otcom","used":"992","hashtags":"#ea4"},
{"id":131,"name":"Zoonoodle","description":"Lymphocyte-rich Hodgkin lymphoma, unspecified site","last_updated":"6/20/2023","page_no":131,"type":"Wrapsafe","used":"3690","hashtags":"#ea2"},
{"id":132,"name":"Rhybox","description":"Nondisp unsp fx unsp lesser toe(s), subs for fx w routn heal","last_updated":"7/10/2022","page_no":132,"type":"Greenlam","used":"06677","hashtags":"#e40"},
{"id":133,"name":"Digitube","description":"Toxic eff of fluorine gas and hydrogen fluoride, asslt, init","last_updated":"4/27/2023","page_no":133,"type":"Zathin","used":"715","hashtags":"#567"},
{"id":134,"name":"Voomm","description":"Occup of pk-up/van injured in clsn w oth and unsp mv in traf","last_updated":"11/12/2022","page_no":134,"type":"Konklab","used":"7","hashtags":"#da7"},
{"id":135,"name":"Yambee","description":"Acute hematogenous osteomyelitis, left shoulder","last_updated":"6/30/2022","page_no":135,"type":"Opela","used":"74","hashtags":"#44b"},
{"id":136,"name":"Zoonder","description":"Displaced segmental fx shaft of ulna, right arm, init","last_updated":"10/14/2022","page_no":136,"type":"Cookley","used":"41060","hashtags":"#be9"},
{"id":137,"name":"Myntrite","description":"Salter-Harris Type IV physeal fracture of upper end radius","last_updated":"4/20/2023","page_no":137,"type":"Tempsoft","used":"4404","hashtags":"#4de"},
{"id":138,"name":"Jabberbean","description":"Unsp fracture of r low leg, subs for clos fx w malunion","last_updated":"7/15/2024","page_no":138,"type":"Hatity","used":"37040","hashtags":"#2e1"},
{"id":139,"name":"Vimbo","description":"Other superficial bite of right foot","last_updated":"9/2/2022","page_no":139,"type":"Viva","used":"49","hashtags":"#667"},
{"id":140,"name":"Abata","description":"Pedl cyc driver injured in nonclsn trnsp accident in traf","last_updated":"7/7/2022","page_no":140,"type":"Prodder","used":"096","hashtags":"#b4b"},
{"id":141,"name":"Edgepulse","description":"Fracture of lateral condyle of humerus","last_updated":"8/4/2023","page_no":141,"type":"Flowdesk","used":"94","hashtags":"#772"},
{"id":142,"name":"Flashset","description":"Unspecified acute noninfective otitis externa","last_updated":"7/10/2024","page_no":142,"type":"Matsoft","used":"7","hashtags":"#390"},
{"id":143,"name":"DabZ","description":"Unsp traum displ spondylolysis of seventh cervcal vert, sqla","last_updated":"11/14/2022","page_no":143,"type":"Fixflex","used":"64","hashtags":"#9d0"},
{"id":144,"name":"Topiczoom","description":"Leakage of other nervous sys device, implant or graft, init","last_updated":"9/16/2022","page_no":144,"type":"Alphazap","used":"2690","hashtags":"#487"},
{"id":145,"name":"InnoZ","description":"Unsp traum displ spondylolysis of sixth cervcal vert, init","last_updated":"8/5/2022","page_no":145,"type":"Trippledex","used":"47175","hashtags":"#b46"},
{"id":146,"name":"Ntags","description":"Complications of liver transplant","last_updated":"9/18/2022","page_no":146,"type":"Sonair","used":"2","hashtags":"#099"},
{"id":147,"name":"Livetube","description":"Exposure to smoke in controlled fire, not in bldg","last_updated":"4/15/2023","page_no":147,"type":"Overhold","used":"4692","hashtags":"#738"},
{"id":148,"name":"Linklinks","description":"Suppurative otitis media, unspecified, left ear","last_updated":"6/10/2022","page_no":148,"type":"Namfix","used":"41490","hashtags":"#d81"},
{"id":149,"name":"Edgetag","description":"Poisoning by salicylates, undetermined, initial encounter","last_updated":"10/22/2022","page_no":149,"type":"Latlux","used":"88","hashtags":"#5bd"},
{"id":150,"name":"Pixonyx","description":"Unsp physl fx upr end rad, unsp arm, subs for fx w malunion","last_updated":"2/3/2023","page_no":150,"type":"Viva","used":"94618","hashtags":"#61c"}
]

export default featured;